server:
  port: 8000
dubbo:
  application:
    name: dubbo-consumer
    version: 1.0
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: -1
  consumer:
    version: 1.0
